In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.random((5,5))

array([[0.16873291, 0.44699402, 0.14674277, 0.77388346, 0.95315203],
       [0.26443914, 0.85441487, 0.54863836, 0.13426396, 0.42614053],
       [0.29958109, 0.47289424, 0.66348836, 0.96566516, 0.99493328],
       [0.13308879, 0.13520937, 0.85381515, 0.25068966, 0.24273099],
       [0.68489499, 0.97732756, 0.48209993, 0.50430472, 0.72888511]])

In [14]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [33]:
a = np.random.random((5,5))*25

In [34]:
a.reshape(5,5)

array([[22.76264386, 22.86285947, 13.00025807, 10.8991776 , 24.52128397],
       [ 8.47192752, 22.83333778,  4.62634724,  8.80787933,  8.86124082],
       [21.4478005 ,  6.18481419, 22.12973743, 13.36879778,  5.74866261],
       [16.02841331,  8.90957833,  2.85494372, 18.59197293,  2.17504867],
       [ 6.12361661,  9.29442276,  8.67901904, 12.37470324, 16.66735592]])

In [35]:
a.sum()

318.2258427079211

In [36]:
a.mean()

12.729033708316845

In [37]:
np.std(a)

6.85450649021022

In [38]:
a.sum(axis=1)

array([94.04622297, 53.6007327 , 68.87981251, 48.55995696, 53.13911757])

In [41]:
b = np.random.random((5,5))*100

In [43]:
np.median(b)

50.92173931424339

In [44]:
np.min(b)

6.799850634455417

In [45]:
np.max(b)

94.85253764833355

In [46]:
c = np.random.random((7,5))*100

In [47]:
np.transpose(c)

array([[80.61432276,  9.33176797, 73.54756213, 58.85701342, 31.75573554,
        92.48159202, 94.70148355],
       [98.86989628, 21.25322205, 51.93606476, 45.85161176, 86.12734626,
        79.77165406, 15.88291558],
       [82.87097909,  3.13189152, 62.38506458,  9.55199429, 15.38170362,
        82.99257253, 94.35282804],
       [ 5.12325942, 19.06322638, 76.08297136, 68.42864391, 81.1172448 ,
        59.78458665, 48.8239233 ],
       [36.53865898, 56.1387606 ,  2.5937256 , 10.65648337, 51.61933204,
        38.41713466, 47.32807617]])

In [48]:
c = np.random.random((7,5))

In [51]:
d = np.random.random((7,5))

In [50]:
c+d

array([[178.56476641, 157.75201962, 167.29330972,  22.55498975,
        112.68947421],
       [ 19.52776362,  51.20564978,  26.62837348,  61.11597988,
        100.39501355],
       [126.42500146, 145.3009177 , 160.38103324, 127.10475404,
         64.24841638],
       [ 86.74341036, 113.20889922,  48.80066436,  82.08469691,
         94.16655891],
       [ 77.01751727, 158.78428719,  82.94448982, 102.30899852,
         87.71252804],
       [130.45601711, 136.0424895 , 168.06283812,  94.03904812,
        134.78624331],
       [183.9163606 ,  17.80500828, 193.05439137,  80.8538951 ,
        142.34814802]])

In [54]:
e = np.random.random((7,5))

In [55]:
f = np.random.random((5,7))

In [56]:
np.matmul(e,f)

array([[0.48473833, 0.75315491, 0.78153762, 0.6096357 , 0.64160405,
        0.85640078, 0.74184984],
       [1.21401145, 1.81049454, 1.79430784, 1.4602403 , 1.49797995,
        1.85739175, 1.39335543],
       [0.61894122, 0.87378709, 1.10212128, 0.88030171, 0.93063182,
        0.87637998, 0.65896239],
       [1.12693437, 1.8718319 , 1.15613947, 1.05992002, 0.94197942,
        1.82928291, 1.25152304],
       [0.70268647, 0.90510083, 1.05701295, 0.74313602, 0.7957195 ,
        1.07055015, 0.75670648],
       [0.74315656, 1.2066948 , 1.09017767, 0.92602389, 0.88185944,
        1.20787208, 0.88201708],
       [1.34799017, 2.12908922, 1.86386433, 1.67813323, 1.78032181,
        1.98649736, 1.6469053 ]])